pop_os_reps = [

]

dot_deb = [
    "wezterm",

]

flatpak = [

]

repositories = [
    "git@github.com:JohnGolgota/dotfiles.git",
    "git@github.com:JohnGolgota/personal-docs.git",
]

apt = [
    "ffmpeg",
    "7zip",
    "jq",
    "poppler-utils",
    "fd-find",
    "ripgrep",
    "fzf",
    "zoxide",
    "imagemagick",

]

todo = [
    "tmux",
    "gitui",
    "zsh",
    "nushell",
    "nvim",
    "zellij",
    "starship",
    "eza",
	"fastfetch",
	"dua-cli",
	"bat",
	"zellij",

]

cargo = [
    "yazi-build",
    "bob-nvim",

]

[[other]]
name = "chezmoi"
method = "dowload binary"

[[other]]
name = "pwsh"
method = "dowload binary"

[[other]]
name = "rust"
method = "wiki"