services:
  tml:
    container_name: tml
    image: jacobsmile/tmodloader1.4
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - 7785:7777
    volumes:
      - ./temp:/data:Z
    environment:
      - TMOD_SHUTDOWN_MESSAGE=Goodbye!
      - TMOD_AUTOSAVE_INTERVAL=15
      - TMOD_AUTODOWNLOAD=2824688072,2824688266,2859639393,2995193002,2839001756,2826052599,2858296368,2828041071,2797518634,2828997816,2707400823,2563309347,2566387467,2565540604,2599842771,2669644269,2619954303,3086919933
      - TMOD_ENABLEDMODS=2824688072,2824688266,2859639393,2995193002,2839001756,2826052599,2858296368,2828041071,2797518634,2828997816,2707400823,2563309347,2566387467,2565540604,2599842771,2669644269,2619954303,3086919933
      - TMOD_MOTD=Welcome to my tModLoader Server!
      - TMOD_PASS=secret
      - TMOD_MAXPLAYERS=8
      - TMOD_WORLDNAME=Earth
      - TMOD_WORLDSIZE=2
      - TMOD_WORLDSEED=not the bees
      - TMOD_DIFFICULTY=2
